### ISSUE TITLE
GPU-accelerated ECSs: text is overlapped

### ISSUE THREAD

**Issue by omelniko** [opentelekomcloud-docs/elastic-cloud-server#21]
Issue on page: https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/umn/source/service_overview/ecs_specifications_and_types/gpu-accelerated_ecss.rst

![image](https://user-images.githubusercontent.com/102943925/161482910-4e0e6f1e-7e7e-44a9-8c26-bf3745c7fa24.png)

**Comment by gtema** [comment]
Since the table is very wide there is no possibility to squeeze everything without ugly wrapping. One possible solution is to add spaces in "Maximum / Assured Bandwidth ...". This will help browser to wrap the line better:

<img width="1166" alt="Screenshot 2022-04-04 at 09 11 15" src="https://user-images.githubusercontent.com/16461884/161491686-887fd805-49a5-4bfb-a138-1ba3b8928a5d.png">

@vladimirhasko what do you think?

**Comment by vladimirhasko** [comment]
I'm not sure why this issue occurred again.
If I remember correctly this has been fixed already.

**Comment by omelniko** [comment]
not an issue
